# Sub2Clash 配置文件示例
# 复制此文件为 config.yaml 并根据需要修改配置

# 服务端口
address: "0.0.0.0:8011"

# 模板配置
meta_template: "https://raw.githubusercontent.com/maihb/sub2clash/refs/heads/main/templates/template_meta.yaml"
clash_template: "https://raw.githubusercontent.com/maihb/sub2clash/refs/heads/main/templates/template_clash.yaml"

# 请求配置
request_retry_times: 3
request_max_file_size: 1048576 # 1MB in bytes

# 缓存配置 (秒)
cache_expire: 300 # 5 minutes

# 日志级别 (debug, info, warn, error)
log_level: "info"

# 短链接长度
short_link_length: 6
